ALTER TABLE products
    ALTER COLUMN created_at TYPE TIMESTAMP DEFAULT NOW();

ALTER TABLE products
    ALTER COLUMN updated_at TYPE TIMESTAMP DEFAULT NOW();

ALTER TABLE user_carts
    ALTER COLUMN created_at TYPE TIMESTAMP DEFAULT NOW();

ALTER TABLE user_carts
    ALTER COLUMN updated_at TYPE TIMESTAMP DEFAULT NOW();

ALTER TABLE cart_items
    ALTER COLUMN created_at TYPE TIMESTAMP DEFAULT NOW();

ALTER TABLE cart_items 
    ALTER COLUMN updated_at TYPE TIMESTAMP DEFAULT NOW();

ALTER TABLE users
    ALTER COLUMN created_at TYPE TIMESTAMP DEFAULT NOW();

ALTER TABLE users
    ALTER COLUMN updated_at TYPE TIMESTAMP DEFAULT NOW();